/**
 *
 *  RestfulNotifiesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulNotifiesCtrl.h"
#include <string>


void RestfulNotifiesCtrl::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Notifies::PrimaryKeyType &&id)
{
    RestfulNotifiesCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulNotifiesCtrl::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Notifies::PrimaryKeyType &&id)
{
    RestfulNotifiesCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulNotifiesCtrl::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Notifies::PrimaryKeyType &&id)
{
    RestfulNotifiesCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulNotifiesCtrl::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulNotifiesCtrlBase::get(req, std::move(callback));
}

void RestfulNotifiesCtrl::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulNotifiesCtrlBase::create(req, std::move(callback));
}
