/**
 *
 *  RestfulElectronsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulElectronsCtrlBase.h"

#include "Electrons.h"
using namespace drogon;
using namespace drogon_model::database_test;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the electrons table.
 */

class RestfulElectronsCtrl: public drogon::HttpController<RestfulElectronsCtrl>, public RestfulElectronsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulElectronsCtrl::getOne,"/electrons/{1}",Get,Options);
    ADD_METHOD_TO(RestfulElectronsCtrl::updateOne,"/electrons/{1}",Put,Options);
    ADD_METHOD_TO(RestfulElectronsCtrl::deleteOne,"/electrons/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulElectronsCtrl::get,"/electrons",Get,Options);
    ADD_METHOD_TO(RestfulElectronsCtrl::create,"/electrons",Post,Options);
    //ADD_METHOD_TO(RestfulElectronsCtrl::update,"/electrons",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Electrons::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Electrons::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Electrons::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
