/**
 *
 *  RestfulChatGroupsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulChatGroupsCtrl.h"
#include <string>


void RestfulChatGroupsCtrl::getOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   ChatGroups::PrimaryKeyType &&id)
{
    RestfulChatGroupsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulChatGroupsCtrl::updateOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      ChatGroups::PrimaryKeyType &&id)
{
    RestfulChatGroupsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulChatGroupsCtrl::deleteOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      ChatGroups::PrimaryKeyType &&id)
{
    RestfulChatGroupsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulChatGroupsCtrl::get(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulChatGroupsCtrlBase::get(req, std::move(callback));
}

void RestfulChatGroupsCtrl::create(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulChatGroupsCtrlBase::create(req, std::move(callback));
}
