/**
 *
 *  RestfulFriendSettingsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulFriendSettingsCtrlBase.h"

#include "FriendSettings.h"
using namespace drogon;
using namespace drogon_model::database_test;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the friend_settings table.
 */

class RestfulFriendSettingsCtrl: public drogon::HttpController<RestfulFriendSettingsCtrl>, public RestfulFriendSettingsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulFriendSettingsCtrl::getOne,"/friendsettings/{1}",Get,Options);
    ADD_METHOD_TO(RestfulFriendSettingsCtrl::updateOne,"/friendsettings/{1}",Put,Options);
    ADD_METHOD_TO(RestfulFriendSettingsCtrl::deleteOne,"/friendsettings/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulFriendSettingsCtrl::get,"/friendsettings",Get,Options);
    ADD_METHOD_TO(RestfulFriendSettingsCtrl::create,"/friendsettings",Post,Options);
    //ADD_METHOD_TO(RestfulFriendSettingsCtrl::update,"/friendsettings",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                FriendSettings::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   FriendSettings::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   FriendSettings::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
