/**
 *
 *  RestfulFriendsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulFriendsCtrl.h"
#include <string>


void RestfulFriendsCtrl::getOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Friends::PrimaryKeyType &&id)
{
    RestfulFriendsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulFriendsCtrl::updateOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Friends::PrimaryKeyType &&id)
{
    RestfulFriendsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulFriendsCtrl::deleteOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Friends::PrimaryKeyType &&id)
{
    RestfulFriendsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulFriendsCtrl::get(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulFriendsCtrlBase::get(req, std::move(callback));
}

void RestfulFriendsCtrl::create(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulFriendsCtrlBase::create(req, std::move(callback));
}
