/**
 *
 *  RestfulFriendSettingsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulFriendSettingsCtrl.h"
#include <string>


void RestfulFriendSettingsCtrl::getOne(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback,
                                       FriendSettings::PrimaryKeyType &&id)
{
    RestfulFriendSettingsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulFriendSettingsCtrl::updateOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          FriendSettings::PrimaryKeyType &&id)
{
    RestfulFriendSettingsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulFriendSettingsCtrl::deleteOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          FriendSettings::PrimaryKeyType &&id)
{
    RestfulFriendSettingsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulFriendSettingsCtrl::get(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulFriendSettingsCtrlBase::get(req, std::move(callback));
}

void RestfulFriendSettingsCtrl::create(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulFriendSettingsCtrlBase::create(req, std::move(callback));
}
