/**
 *
 *  RestfulGroupMembersCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulGroupMembersCtrlBase.h"

#include "GroupMembers.h"
using namespace drogon;
using namespace drogon_model::database_test;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the group_members table.
 */

class RestfulGroupMembersCtrl: public drogon::HttpController<RestfulGroupMembersCtrl>, public RestfulGroupMembersCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulGroupMembersCtrl::getOne,"/groupmembers/{1}",Get,Options);
    ADD_METHOD_TO(RestfulGroupMembersCtrl::updateOne,"/groupmembers/{1}",Put,Options);
    ADD_METHOD_TO(RestfulGroupMembersCtrl::deleteOne,"/groupmembers/{1}",Delete,Options);
    ADD_METHOD_TO(RestfulGroupMembersCtrl::get,"/groupmembers",Get,Options);
    ADD_METHOD_TO(RestfulGroupMembersCtrl::create,"/groupmembers",Post,Options);
    //ADD_METHOD_TO(RestfulGroupMembersCtrl::update,"/groupmembers",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                GroupMembers::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   GroupMembers::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   GroupMembers::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
