/**
 *
 *  RestfulElectronsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulElectronsCtrl.h"
#include <string>


void RestfulElectronsCtrl::getOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Electrons::PrimaryKeyType &&id)
{
    RestfulElectronsCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulElectronsCtrl::updateOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Electrons::PrimaryKeyType &&id)
{
    RestfulElectronsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulElectronsCtrl::deleteOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Electrons::PrimaryKeyType &&id)
{
    RestfulElectronsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulElectronsCtrl::get(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulElectronsCtrlBase::get(req, std::move(callback));
}

void RestfulElectronsCtrl::create(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulElectronsCtrlBase::create(req, std::move(callback));
}
