/**
 *
 *  RestfulGroupMembersCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulGroupMembersCtrl.h"
#include <string>


void RestfulGroupMembersCtrl::getOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     GroupMembers::PrimaryKeyType &&id)
{
    RestfulGroupMembersCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulGroupMembersCtrl::updateOne(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback,
                                        GroupMembers::PrimaryKeyType &&id)
{
    RestfulGroupMembersCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulGroupMembersCtrl::deleteOne(const HttpRequestPtr &req,
                                        std::function<void(const HttpResponsePtr &)> &&callback,
                                        GroupMembers::PrimaryKeyType &&id)
{
    RestfulGroupMembersCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulGroupMembersCtrl::get(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulGroupMembersCtrlBase::get(req, std::move(callback));
}

void RestfulGroupMembersCtrl::create(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulGroupMembersCtrlBase::create(req, std::move(callback));
}
