/**
 *
 *  User.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>

#include "Users.h"
using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::database_test;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the users table.
 */

namespace api::v1
{

  class User : public drogon::HttpController<User>
  {
  public:
    METHOD_LIST_BEGIN
    METHOD_ADD(User::login, "/login", Post, Options);
    METHOD_ADD(User::logout, "/logout", Get, Options);
    METHOD_ADD(User::registerHandler, "/register", Post, Options);
    METHOD_LIST_END

    void login(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void logout(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void registerHandler(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);

  private:
    orm::DbClientPtr getDbClient()
    {
      return drogon::app().getDbClient(dbClientName_);
    }

    nosql::RedisClientPtr getRedisClient()
    {
      return drogon::app().getRedisClient(redieClientName_);
    }

  private:
    const std::string dbClientName_{"default"};
    const std::string redieClientName_{"default"};
  };

}
