/**
 *
 *  UserCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>

#include "Users.h"
using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::database_test;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the users table.
 */

namespace api::v1
{

  class User : public drogon::HttpController<User>
  {
  public:
    METHOD_LIST_BEGIN
    METHOD_ADD(User::login, "/login", Post, Options);
    METHOD_ADD(User::logout, "/logout", Get, Options, "api::v1::filters::JwtFilter");
    METHOD_ADD(User::create, "", Post, Options);
    METHOD_ADD(User::deleteOne, "/op/{1}", Delete, Options, "api::v1::filters::JwtFilter");
    METHOD_ADD(User::updateOne, "/op/{1}", Put, Options, "api::v1::filters::JwtFilter");
    METHOD_ADD(User::getOne, "/op/{1}", Get, Options, "api::v1::filters::JwtFilter");
    METHOD_LIST_END

    void login(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void logout(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void deleteOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void updateOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Users::PrimaryKeyType &&id);

  private:
    orm::DbClientPtr getDbClient()
    {
      return drogon::app().getDbClient(dbClientName_);
    }

    nosql::RedisClientPtr getRedisClient()
    {
      return drogon::app().getRedisClient(redieClientName_);
    }

  private:
    const std::string dbClientName_{"default"};
    const std::string redieClientName_{"default"};
  };

}
